import type { BranchListItem, BranchesPageResponse } from './features/branches/branchesTypes'
import type { TenantListItem, TenantsPageResponse } from './features/tenants/tenantsTypes'

export const MOCK_TENANTS: TenantListItem[] = [
  {
    tenantId: 'tenant-001',
    tenantCode: 'HOSP-RIYADH',
    tenantName: 'Riyadh General Hospital',
    tenantNameAr: 'مستشفى الرياض العام',
    organizationType: 'HOSPITAL',
    licenseNumber: 'MOH-2023-0451',
    status: 'ACTIVE',
    maxUsers: 500,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-03-10T12:30:00Z',
  },
  {
    tenantId: 'tenant-002',
    tenantCode: 'NET-SAUDI',
    tenantName: 'Saudi Health Network',
    tenantNameAr: 'شبكة الصحة السعودية',
    organizationType: 'NETWORK',
    licenseNumber: 'MOH-2022-1102',
    status: 'ACTIVE',
    maxUsers: 1000,
    createdAt: '2022-06-01T09:00:00Z',
    updatedAt: '2024-01-20T11:00:00Z',
  },
  {
    tenantId: 'tenant-003',
    tenantCode: 'CLINIC-JEDDAH',
    tenantName: 'Jeddah Medical Clinic',
    tenantNameAr: 'عيادة جدة الطبية',
    organizationType: 'CLINIC',
    licenseNumber: 'MOH-2024-0087',
    status: 'ACTIVE',
    maxUsers: 100,
    createdAt: '2024-01-10T07:00:00Z',
    updatedAt: '2024-05-05T14:00:00Z',
  },
  {
    tenantId: 'tenant-004',
    tenantCode: 'LAB-DAMMAM',
    tenantName: 'Dammam Central Labs',
    tenantNameAr: 'مختبرات الدمام المركزية',
    organizationType: 'LAB',
    licenseNumber: 'MOH-2021-0760',
    status: 'INACTIVE',
    maxUsers: 50,
    createdAt: '2021-09-20T10:00:00Z',
    updatedAt: '2023-11-01T09:15:00Z',
  },
]

export const MOCK_BRANCHES: BranchListItem[] = [
  {
    branchId: 'branch-001',
    branchCode: 'RGH-HQ',
    branchName: 'Riyadh General Hospital – Headquarters',
    branchNameAr: 'مستشفى الرياض العام – المقر الرئيسي',
    branchType: 'MAIN',
    isHeadquarters: true,
    licenseNumber: 'MOH-BR-2023-001',
    contactEmail: 'hq@rgh.sa',
    contactPhone: '+966 11 100 0001',
    address: 'King Fahd Road, Al Olaya District',
    city: 'Riyadh',
    region: 'RIYADH',
    status: 'ACTIVE',
    tenantId: 'tenant-001',
    tenantName: 'Riyadh General Hospital',
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-03-10T12:30:00Z',
  },
  {
    branchId: 'branch-002',
    branchCode: 'RGH-NORTH',
    branchName: 'Riyadh General – North Branch',
    branchNameAr: 'مستشفى الرياض العام – فرع الشمال',
    branchType: 'REGIONAL',
    isHeadquarters: false,
    licenseNumber: 'MOH-BR-2023-002',
    contactEmail: 'north@rgh.sa',
    contactPhone: '+966 11 100 0002',
    address: 'Prince Sultan Road, Al Nakheel',
    city: 'Riyadh',
    region: 'RIYADH',
    status: 'ACTIVE',
    tenantId: 'tenant-001',
    tenantName: 'Riyadh General Hospital',
    createdAt: '2023-03-01T09:00:00Z',
    updatedAt: '2024-02-14T10:00:00Z',
  },
  {
    branchId: 'branch-003',
    branchCode: 'RGH-SAT1',
    branchName: 'Riyadh General – Al Malaz Satellite',
    branchNameAr: 'مستشفى الرياض العام – فرع الملز',
    branchType: 'SATELLITE',
    isHeadquarters: false,
    licenseNumber: null,
    contactEmail: 'malaz@rgh.sa',
    contactPhone: '+966 11 100 0003',
    address: 'Al Malaz District, Block 12',
    city: 'Riyadh',
    region: 'RIYADH',
    status: 'INACTIVE',
    tenantId: 'tenant-001',
    tenantName: 'Riyadh General Hospital',
    createdAt: '2023-06-15T11:00:00Z',
    updatedAt: '2023-12-01T08:00:00Z',
  },
  {
    branchId: 'branch-004',
    branchCode: 'SHN-HQ',
    branchName: 'Saudi Health Network – Main Office',
    branchNameAr: 'شبكة الصحة السعودية – المكتب الرئيسي',
    branchType: 'MAIN',
    isHeadquarters: true,
    licenseNumber: 'MOH-BR-2022-010',
    contactEmail: 'info@shn.sa',
    contactPhone: '+966 12 200 0001',
    address: 'Corniche Road, Al Hamra',
    city: 'Jeddah',
    region: 'MAKKAH',
    status: 'ACTIVE',
    tenantId: 'tenant-002',
    tenantName: 'Saudi Health Network',
    createdAt: '2022-06-01T09:00:00Z',
    updatedAt: '2024-01-20T11:00:00Z',
  },
  {
    branchId: 'branch-005',
    branchCode: 'SHN-MAKKAH',
    branchName: 'Saudi Health Network – Makkah',
    branchNameAr: 'شبكة الصحة السعودية – مكة المكرمة',
    branchType: 'REGIONAL',
    isHeadquarters: false,
    licenseNumber: 'MOH-BR-2022-011',
    contactEmail: 'makkah@shn.sa',
    contactPhone: '+966 12 200 0002',
    address: 'Ibrahim Al Khalil Road',
    city: 'Makkah',
    region: 'MAKKAH',
    status: 'ACTIVE',
    tenantId: 'tenant-002',
    tenantName: 'Saudi Health Network',
    createdAt: '2022-08-10T10:00:00Z',
    updatedAt: '2024-01-15T09:00:00Z',
  },
  {
    branchId: 'branch-006',
    branchCode: 'JMC-HQ',
    branchName: 'Jeddah Medical Clinic – Main',
    branchNameAr: 'عيادة جدة الطبية – الرئيسية',
    branchType: 'MAIN',
    isHeadquarters: true,
    licenseNumber: 'MOH-BR-2024-005',
    contactEmail: 'main@jmc.sa',
    contactPhone: '+966 12 300 0001',
    address: 'Tahlia Street, Al Rawdah',
    city: 'Jeddah',
    region: 'MAKKAH',
    status: 'ACTIVE',
    tenantId: 'tenant-003',
    tenantName: 'Jeddah Medical Clinic',
    createdAt: '2024-01-10T07:00:00Z',
    updatedAt: '2024-05-05T14:00:00Z',
  },
  {
    branchId: 'branch-007',
    branchCode: 'DCL-HQ',
    branchName: 'Dammam Central Labs – HQ',
    branchNameAr: 'مختبرات الدمام المركزية – المقر',
    branchType: 'MAIN',
    isHeadquarters: true,
    licenseNumber: 'MOH-BR-2021-050',
    contactEmail: 'info@dcl.sa',
    contactPhone: '+966 13 400 0001',
    address: 'King Saud Street, Al Faisaliyah',
    city: 'Dammam',
    region: 'EASTERN_PROVINCE',
    status: 'INACTIVE',
    tenantId: 'tenant-004',
    tenantName: 'Dammam Central Labs',
    createdAt: '2021-09-20T10:00:00Z',
    updatedAt: '2023-11-01T09:15:00Z',
  },
]

export const MOCK_BRANCHES_PAGE: BranchesPageResponse = {
  content: MOCK_BRANCHES,
  totalElements: MOCK_BRANCHES.length,
  totalPages: 1,
  page: 0,
  size: 20,
}

export const MOCK_TENANTS_PAGE: TenantsPageResponse = {
  content: MOCK_TENANTS,
  totalElements: MOCK_TENANTS.length,
  totalPages: 1,
  page: 0,
  size: 20,
}
